/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JLabel;

/**
 *
 * @author Przemysław
 */
public class NewJPanel extends javax.swing.JPanel {

    JLabel l;
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        //initComponents();
        l = new JLabel("AAA");//new ImageIcon(ResourceLoader.class.getResource("/images/Green-Gradient-Background.jpg")));
        super.add(l);
        l.setLayout(new BorderLayout());
    }

    @Override
    public Component add(Component c){
        if(l!=null && c!=null){
            this.l.add(c);
        }
        return c;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
